# Generated by EnvironmentDetailAssignment Tool
# Environment: Production
# Generated: 2025-09-26 18:50:58

# Global Environment Parameters
$EnvironmentName = "Production"
$NetworkPrefix = "10.0.0.0/16"
$VlanBase = 1000
$DeviceSuffix = "prod"
$ManagementVlan = 1001
$NtpServers = @("10.0.1.1", "10.0.1.2")
$DnsServers = @("10.0.1.3", "10.0.1.4")

# Device-Specific Parameters
$TOR1_Hostname = "TOR-1-prod"
$TOR1_ManagementIP = "10.0.1.10"
$TOR1_Location = "DataCenter-01"
$TOR2_Hostname = "TOR-2-prod"
$TOR2_ManagementIP = "10.0.1.11"
$TOR2_Location = "DataCenter-01"
$SPINE1_Hostname = "SPINE-1-prod"
$SPINE1_ManagementIP = "10.0.1.20"
$SPINE1_Location = "DataCenter-01"
