name: Build Executables

on:
  push:
    branches: [ main, dev/nl/newDesignv1 ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: network-config-generator.exe
            asset_name: network-config-generator-windows-amd64
          - os: ubuntu-latest
            artifact_name: network-config-generator
            asset_name: network-config-generator-linux-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt found, installing basic dependencies"
      shell: bash

    - name: Create requirements.txt if not exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "jinja2>=3.0.0" > requirements.txt
        fi
      shell: bash

    - name: Test the application
      run: |
        python src/main.py --help
      shell: bash

    - name: Build executable with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        if (Test-Path "src/network_config_generator.spec") {
          Write-Host "Using existing spec file..."
          cd src
          pyinstaller network_config_generator.spec --clean
        } else {
          Write-Host "Building with manual configuration..."
          pyinstaller --onefile --clean --name network-config-generator `
            --add-data "input;input" `
            --hidden-import=jinja2 `
            --hidden-import=jinja2.ext `
            --hidden-import=convertors `
            --hidden-import=convertors.convertors_lab_switch_json `
            --collect-submodules=convertors `
            --paths=src `
            src/main.py
        }
        Write-Host "Checking build results..."
        Get-ChildItem dist/ -Force -ErrorAction SilentlyContinue
        if (Test-Path "dist/network-config-generator.exe") {
          $size = (Get-Item "dist/network-config-generator.exe").Length / 1MB
          Write-Host "Executable size: $($size.ToString('F2')) MB"
        } else {
          Write-Host "ERROR: Executable was not created!"
          exit 1
        }
      shell: powershell

    - name: Build executable with PyInstaller (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        if [ -f "src/network_config_generator.spec" ]; then
          echo "Using existing spec file..."
          cd src
          pyinstaller network_config_generator.spec --clean
        else
          echo "Building with manual configuration..."
          pyinstaller --onefile --clean \
            --name network-config-generator \
            --add-data "input:input" \
            --hidden-import=jinja2 \
            --hidden-import=jinja2.ext \
            --hidden-import=convertors \
            --hidden-import=convertors.convertors_lab_switch_json \
            --collect-submodules=convertors \
            --paths=src \
            src/main.py
        fi
        echo "Checking build results..."
        ls -la dist/
      shell: bash

    - name: Test executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Write-Host "Testing Windows executable..."
        Write-Host "Current directory contents:"
        Get-ChildItem . -Force
        Write-Host "Checking for executable in various locations..."
        if (Test-Path "dist/network-config-generator.exe") {
          Write-Host "Found in dist/ - running help command..."
          & "dist/network-config-generator.exe" --help
        } elseif (Test-Path "src/dist/network-config-generator.exe") {
          Write-Host "Found in src/dist/ - running help command..."
          & "src/dist/network-config-generator.exe" --help
        } else {
          Write-Host "ERROR: Executable not found in expected locations!"
          Write-Host "Checking src/ directory:"
          Get-ChildItem src/ -Force -ErrorAction SilentlyContinue
          Write-Host "Checking src/dist/ directory:"
          Get-ChildItem src/dist/ -Force -ErrorAction SilentlyContinue
          exit 1
        }
      shell: powershell

    - name: Test executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        echo "Testing Unix executable..."
        echo "Current directory contents:"
        ls -la
        echo "Checking for executable in various locations..."
        if [ -f "dist/network-config-generator" ]; then
          echo "Found in dist/ - making it executable and running help command..."
          chmod +x ./dist/network-config-generator
          ./dist/network-config-generator --help
        elif [ -f "src/dist/network-config-generator" ]; then
          echo "Found in src/dist/ - making it executable and running help command..."
          chmod +x ./src/dist/network-config-generator
          ./src/dist/network-config-generator --help
        else
          echo "ERROR: Executable not found in expected locations!"
          echo "Checking src/ directory:"
          ls -la src/ || echo "src/ does not exist"
          echo "Checking src/dist/ directory:"
          ls -la src/dist/ || echo "src/dist/ does not exist"
          echo "Looking for any network-config-generator files:"
          find . -name "*network-config-generator*" -type f 2>/dev/null || echo "No matching files found"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: |
          dist/${{ matrix.artifact_name }}
          src/dist/${{ matrix.artifact_name }}

  # Create release if this is a tag
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Display structure of downloaded files
      run: ls -la ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          ./artifacts/network-config-generator-windows-amd64/network-config-generator.exe
          ./artifacts/network-config-generator-linux-amd64/network-config-generator
        body: |
          ## Network Switch Config Generator ${{ github.ref_name }}
          
          ### Download Instructions
          1. Download the appropriate executable for your operating system
          2. Make it executable (Linux): `chmod +x network-config-generator`
          3. Run: `./network-config-generator --help`
          
          ### Usage Examples
          ```bash
          # Convert lab format and generate configs
          ./network-config-generator --input_json lab_input.json --output_folder output/
          
          # Use standard format directly
          ./network-config-generator --input_json standard_input.json --output_folder output/
          
          # Use custom convertor
          ./network-config-generator --input_json lab_input.json --convertor my.custom.convertor
          ```
          
          ### Features
          - ✅ Auto-detects input format (lab vs standard)
          - ✅ Converts lab format to standard format automatically
          - ✅ Generates network switch configurations
          - ✅ Supports custom convertors
          - ✅ Multi-switch support
          - ✅ Cross-platform executables
        draft: false
        prerelease: false
