name: Create Artifact

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/**.md'

jobs:
  build-project:
    strategy:
      matrix:
        GO_VERSION: [1.20.0]
        OS_WINDOWS: [windows]
        OS_LINUX: [linux]
        ARTIFACT_NAME: [SwitchConfigGenerator]
        ARTIFACT_DIR: [SwitchConfigGenerator]

    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Test
        run: |
          cd ./src
          ls -R
          go test -v

      - name: Build Windows Artifact
        run: |
          cd ./src
          go mod tidy
          GOOS=${{ matrix.OS_WINDOWS }} GOARCH=amd64 go build -buildvcs=false -o ./${{ matrix.ARTIFACT_DIR }}/${{ matrix.OS_WINDOWS }}/

      - name: Build Linux Artifact
        run: |
          cd ./src
          go mod tidy
          GOOS=${{ matrix.OS_LINUX }} GOARCH=amd64 go build -buildvcs=false -o ./${{ matrix.ARTIFACT_DIR }}/${{ matrix.OS_LINUX }}/

      - name: Copy Essential Files
        run: |
          cp -R ./input ./src/${{ matrix.ARTIFACT_DIR }}/
          ls ./src/${{ matrix.ARTIFACT_DIR }}/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ARTIFACT_DIR }}
          path: ./src/${{ matrix.ARTIFACT_DIR }}/
